PICTURE_TYPE = {
    0: "Other",
    1: "32x32 pixels 'file icon' (PNG only)",
    2: "Other file icon",
    3: "Cover (front)",
    4: "Cover (back)",
    5: "Leaflet page",
    6: "Media (e.g. label side of CD)",
    7: "Lead artist/lead performer/soloist",
    8: "Artist/performer",
    9: "Conductor",
    "A": "Band/Orchestra",
    "B": "Composer",
    "C": "Lyricist/text writer",
    "D": "Recording Location",
    "E": "During recording",
    "F": "During performance",
    10: "Movie/video screen capture",
    11: "A bright coloured fish",
    12: "Illustration",
    13: "Band/artist logotype",
    14: "Publisher/Studio logotype",
}
